services:
  django:
    build: .
    container_name: django
    command: bash -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/usr/src/web-service/
    ports:
      - 8000:8000
    depends_on:
      - pgdb
    env_file:
      - .env

  pgdb:
    image: postgres
    container_name: pgdb
    volumes:
      - pg_data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=${SQL_DATABASE}
#      - POSTGRES_USER=${SQL_USER}
#      - POSTGRES_PASSWORD=${SQL_PASSWORD}

volumes:
  pg_data:
