# Generated by Django 3.2.4 on 2021-07-05 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название: ')),
                ('descriptions', models.TextField(max_length=280, verbose_name='Описание: ')),
                ('group_muscle', models.CharField(max_length=30, verbose_name='Группа мышц: ')),
                ('photo', models.ImageField(upload_to='photos/exercise', verbose_name='Фото: ')),
            ],
            options={
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название: ')),
                ('descriptions', models.TextField(verbose_name='Описание: ')),
                ('fats', models.IntegerField(verbose_name='Жиры: ')),
                ('proteins', models.IntegerField(verbose_name='Белки: ')),
                ('carbohydrates', models.IntegerField(verbose_name='Углеводы: ')),
                ('photo', models.ImageField(upload_to='photos/food', verbose_name='Фото: ')),
            ],
            options={
                'verbose_name_plural': 'Еда',
            },
        ),
        migrations.CreateModel(
            name='vitamins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название: ')),
                ('role', models.TextField(max_length=280, verbose_name='Роль: ')),
                ('disadvantage', models.TextField(max_length=280, verbose_name='Недостаток: ')),
            ],
            options={
                'verbose_name_plural': 'Витамины',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('type_body', models.CharField(max_length=30)),
                ('target', models.CharField(blank=True, max_length=30)),
                ('fats', models.IntegerField(blank=True)),
                ('proteins', models.IntegerField(blank=True)),
                ('carbohydrates', models.IntegerField(blank=True)),
                ('sex', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='food_vit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitCalendar.food')),
                ('id_vitamins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitCalendar.vitamins')),
            ],
            options={
                'verbose_name_plural': 'Витамины в еде',
            },
        ),
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата: ')),
                ('day_of_week', models.CharField(max_length=30, verbose_name='День недели: ')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitCalendar.users')),
            ],
            options={
                'verbose_name_plural': 'Дни',
            },
        ),
        migrations.CreateModel(
            name='basket_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_weight', models.IntegerField(verbose_name='Вес еды: ')),
                ('id_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitCalendar.day')),
                ('id_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_food_fv', to='FitCalendar.food_vit')),
                ('id_food_vit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_food_vit_fv', to='FitCalendar.food_vit')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_day', to='FitCalendar.day')),
                ('id_vitamins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_vitamins_fv', to='FitCalendar.food_vit')),
            ],
            options={
                'verbose_name_plural': 'Корзина еды',
            },
        ),
        migrations.CreateModel(
            name='basket_exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_day_in_be', to='FitCalendar.day')),
                ('id_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitCalendar.exercise')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitCalendar.day')),
            ],
            options={
                'verbose_name_plural': 'Корзина упражнений',
            },
        ),
    ]
