# Generated by Django 3.2.4 on 2021-06-24 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descriptions', models.TextField(max_length=280)),
                ('group_muscle', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='photos/exercise')),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descriptions', models.TextField()),
                ('fats', models.IntegerField()),
                ('proteins', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos/food')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('type_body', models.CharField(max_length=30)),
                ('target', models.CharField(blank=True, max_length=30)),
                ('fats', models.IntegerField(blank=True)),
                ('proteins', models.IntegerField(blank=True)),
                ('carbohydrates', models.IntegerField(blank=True)),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='vitamins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.TextField(max_length=280)),
                ('disadvantage', models.TextField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='food_vit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitCalendar.food')),
                ('id_vitamins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitCalendar.vitamins')),
            ],
        ),
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_of_week', models.CharField(max_length=30)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitCalendar.users')),
            ],
        ),
        migrations.CreateModel(
            name='basket_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_weight', models.IntegerField()),
                ('id_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitCalendar.day')),
                ('id_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_food_fv', to='FitCalendar.food_vit')),
                ('id_food_vit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_food_vit_fv', to='FitCalendar.food_vit')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_day', to='FitCalendar.day')),
                ('id_vitamins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_vitamins_fv', to='FitCalendar.food_vit')),
            ],
        ),
        migrations.CreateModel(
            name='basket_exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_day_in_be', to='FitCalendar.day')),
                ('id_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitCalendar.exercise')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitCalendar.day')),
            ],
        ),
    ]
