# Generated by Django 3.2.4 on 2024-01-15 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FitCalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='day')),
            ],
            options={
                'verbose_name_plural': 'Корзина упражнений',
            },
        ),
        migrations.CreateModel(
            name='BasketFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='day')),
                ('food_weight', models.IntegerField(verbose_name='Вес еды: ')),
            ],
            options={
                'verbose_name_plural': 'Корзина еды',
            },
        ),
        migrations.RemoveField(
            model_name='basket_food',
            name='id_day',
        ),
        migrations.RemoveField(
            model_name='basket_food',
            name='id_food',
        ),
        migrations.RemoveField(
            model_name='basket_food',
            name='id_food_vit',
        ),
        migrations.RemoveField(
            model_name='basket_food',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='basket_food',
            name='id_vitamins',
        ),
        migrations.RemoveField(
            model_name='day',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='food_vit',
            name='id_food',
        ),
        migrations.RemoveField(
            model_name='food_vit',
            name='id_vitamins',
        ),
        migrations.AddField(
            model_name='food',
            name='vitamins',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='FitCalendar.vitamins'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='descriptions',
            field=models.TextField(max_length=280, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='group_muscle',
            field=models.CharField(max_length=30, verbose_name='Группа мышц'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.IntegerField(verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='food',
            name='descriptions',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.IntegerField(verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(upload_to='photos/food', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=models.IntegerField(verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='users',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='type_body',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='weight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vitamins',
            name='disadvantage',
            field=models.TextField(max_length=280, verbose_name='Недостаток'),
        ),
        migrations.AlterField(
            model_name='vitamins',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vitamins',
            name='role',
            field=models.TextField(max_length=280, verbose_name='Роль'),
        ),
        migrations.DeleteModel(
            name='basket_exercise',
        ),
        migrations.DeleteModel(
            name='basket_food',
        ),
        migrations.DeleteModel(
            name='day',
        ),
        migrations.DeleteModel(
            name='food_vit',
        ),
        migrations.AddField(
            model_name='basketfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitCalendar.food', verbose_name='food'),
        ),
        migrations.AddField(
            model_name='basketfood',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='basketexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitCalendar.exercise'),
        ),
        migrations.AddField(
            model_name='basketexercise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
