# Generated by Django 3.2.4 on 2024-01-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitCalendar', '0002_auto_20240115_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='photo',
            field=models.ImageField(upload_to='photos/exercise', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='VitaminsInFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, verbose_name='Количество')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FitCalendar.food', verbose_name='еда')),
                ('vitamins', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FitCalendar.vitamins', verbose_name='витамины')),
            ],
        ),
    ]
