# Generated by Django 3.2.4 on 2024-01-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitCalendar', '0003_auto_20240115_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='vitamins',
        ),
        migrations.AddField(
            model_name='food',
            name='vitamins',
            field=models.ManyToManyField(through='FitCalendar.VitaminsInFood', to='FitCalendar.Vitamins'),
        ),
    ]
