# Generated by Django 3.2.4 on 2024-01-15 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FitCalendar', '0004_auto_20240115_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketexercise',
            name='day',
        ),
        migrations.RemoveField(
            model_name='basketexercise',
            name='id',
        ),
        migrations.RemoveField(
            model_name='basketexercise',
            name='user',
        ),
        migrations.RemoveField(
            model_name='basketfood',
            name='day',
        ),
        migrations.RemoveField(
            model_name='basketfood',
            name='id',
        ),
        migrations.RemoveField(
            model_name='basketfood',
            name='user',
        ),
        migrations.AlterField(
            model_name='food',
            name='vitamins',
            field=models.ManyToManyField(through='FitCalendar.VitaminsInFood', to='FitCalendar.Vitamins'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='basketexercise',
            name='basket_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FitCalendar.basket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basketfood',
            name='basket_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FitCalendar.basket'),
            preserve_default=False,
        ),
    ]
